dist: trusty
language: java
sudo: true
jdk:
   - oraclejdk8
addons:
  postgresql: "11"
  apt:
    packages:
    - postgresql-11
    - postgresql-client-11
env:
  global:
  - PGPORT=5433
  - PGUSER=travis
before_install:
- psql -c 'create database wallet;' -U postgres
- chmod +x mvnw
- export TZ=Brazil/East
deploy:
  provider: heroku
  api_key:
    secure: $SECURE_KEY
  app: $APP