dist: trusty
language: java
sudo: true
jdk:
   - oraclejdk8
services:
  - memcached
before_install:
- psql -c 'create database wallet;' -U postgres
- chmod +x mvnw
- export TZ=Brazil/East
deploy:
  provider: heroku
  api_key:
    secure: $SECURE_KEY
  app: $APP