dist: trusty
language: java
sudo: true
jdk:
   - oraclejdk8
services:
  - postgresql
addons:
  postgresql: "10"
  apt:
    packages:
    - postgresql-10
    - postgresql-client-10
env:
  global:
  - PGPORT=5432
  - PGUSER=postgres
before_install:
- psql -c 'create database wallet;' -U postgres
- chmod +x mvnw
- export TZ=Brazil/East
deploy:
  provider: heroku
  api_key:
    secure: $SECURE_KEY
  app: $APP